
/* Autogenerated file, do not edit! */

/* eslint-disable */
import { AztecAddress, CompleteAddress } from '@aztec/aztec.js/addresses';
import { type AbiType, type AztecAddressLike, type ContractArtifact, EventSelector, decodeFromAbi, type EthAddressLike, type FieldLike, type FunctionSelectorLike, loadContractArtifact, loadContractArtifactForPublic, type NoirCompiledContract, type OptionLike, type U128Like, type WrappedFieldLike } from '@aztec/aztec.js/abi';
import { Contract, ContractBase, ContractFunctionInteraction, type ContractMethod, type ContractStorageLayout, DeployMethod } from '@aztec/aztec.js/contracts';
import { EthAddress } from '@aztec/aztec.js/addresses';
import { Fr, Point } from '@aztec/aztec.js/fields';
import { type PublicKey, PublicKeys } from '@aztec/aztec.js/keys';
import type { Wallet } from '@aztec/aztec.js/wallet';
import SchnorrInitializerlessAccountContractArtifactJson from '../target/schnorr_initializerless_account_contract-SchnorrInitializerlessAccount.json' with { type: 'json' };
export const SchnorrInitializerlessAccountContractArtifact = loadContractArtifact(SchnorrInitializerlessAccountContractArtifactJson as NoirCompiledContract);



/**
 * Type-safe interface for contract SchnorrInitializerlessAccount;
 */
export class SchnorrInitializerlessAccountContract extends ContractBase {
  
  private constructor(
    address: AztecAddress,
    wallet: Wallet,
  ) {
    super(address, SchnorrInitializerlessAccountContractArtifact, wallet);
  }
  

  
  /**
   * Creates a contract instance.
   * @param address - The deployed contract's address.
   * @param wallet - The wallet to use when interacting with the contract.
   * @returns A new Contract instance.
   */
  public static at(
    address: AztecAddress,
    wallet: Wallet,
  ): SchnorrInitializerlessAccountContract {
    return Contract.at(address, SchnorrInitializerlessAccountContract.artifact, wallet) as SchnorrInitializerlessAccountContract;
  }

  
  /**
   * Creates a tx to deploy a new instance of this contract.
   */
  public static deploy(wallet: Wallet, ) {
    return new DeployMethod<SchnorrInitializerlessAccountContract>(PublicKeys.default(), wallet, SchnorrInitializerlessAccountContractArtifact, (instance, wallet) => SchnorrInitializerlessAccountContract.at(instance.address, wallet), Array.from(arguments).slice(1));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified public keys hash to derive the address.
   */
  public static deployWithPublicKeys(publicKeys: PublicKeys, wallet: Wallet, ) {
    return new DeployMethod<SchnorrInitializerlessAccountContract>(publicKeys, wallet, SchnorrInitializerlessAccountContractArtifact, (instance, wallet) => SchnorrInitializerlessAccountContract.at(instance.address, wallet), Array.from(arguments).slice(2));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified constructor method.
   */
  public static deployWithOpts<M extends keyof SchnorrInitializerlessAccountContract['methods']>(
    opts: { publicKeys?: PublicKeys; method?: M; wallet: Wallet },
    ...args: Parameters<SchnorrInitializerlessAccountContract['methods'][M]>
  ) {
    return new DeployMethod<SchnorrInitializerlessAccountContract>(
      opts.publicKeys ?? PublicKeys.default(),
      opts.wallet,
      SchnorrInitializerlessAccountContractArtifact,
      (instance, wallet) => SchnorrInitializerlessAccountContract.at(instance.address, wallet),
      Array.from(arguments).slice(1),
      opts.method ?? 'constructor',
    );
  }
  

  
  /**
   * Returns this contract's artifact.
   */
  public static get artifact(): ContractArtifact {
    return SchnorrInitializerlessAccountContractArtifact;
  }

  /**
   * Returns this contract's artifact with public bytecode.
   */
  public static get artifactForPublic(): ContractArtifact {
    return loadContractArtifactForPublic(SchnorrInitializerlessAccountContractArtifactJson as NoirCompiledContract);
  }
  

  

  /** Type-safe wrappers for the public methods exposed by the contract. */
  public declare methods: {
    
    /** entrypoint(app_payload: struct, fee_payment_method: integer, cancellable: boolean) */
    entrypoint: ((app_payload: { function_calls: { args_hash: FieldLike, function_selector: FunctionSelectorLike, target_address: AztecAddressLike, is_public: boolean, hide_msg_sender: boolean, is_static: boolean }[], tx_nonce: FieldLike }, fee_payment_method: (bigint | number), cancellable: boolean) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_signing_public_key() */
    get_signing_public_key: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** lookup_validity(consumer: struct, inner_hash: field) */
    lookup_validity: ((consumer: AztecAddressLike, inner_hash: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** offchain_receive(messages: struct) */
    offchain_receive: ((messages: { ciphertext: FieldLike[], recipient: AztecAddressLike, tx_hash: OptionLike<FieldLike>, anchor_block_timestamp: (bigint | number) }[]) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** public_dispatch(selector: field) */
    public_dispatch: ((selector: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** store_immutables(capsule_data: array) */
    store_immutables: ((capsule_data: FieldLike[]) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** sync_state(scope: struct) */
    sync_state: ((scope: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** verify_private_authwit(inner_hash: field) */
    verify_private_authwit: ((inner_hash: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;
  };

  
}
