
/* Autogenerated file, do not edit! */

/* eslint-disable */
import { AztecAddress, CompleteAddress } from '@aztec/aztec.js/addresses';
import { type AbiType, type AztecAddressLike, type ContractArtifact, EventSelector, decodeFromAbi, type EthAddressLike, type FieldLike, type FunctionSelectorLike, loadContractArtifact, loadContractArtifactForPublic, type NoirCompiledContract, type OptionLike, type U128Like, type WrappedFieldLike } from '@aztec/aztec.js/abi';
import { Contract, ContractBase, ContractFunctionInteraction, type ContractMethod, type ContractStorageLayout, DeployMethod } from '@aztec/aztec.js/contracts';
import { EthAddress } from '@aztec/aztec.js/addresses';
import { Fr, Point } from '@aztec/aztec.js/fields';
import { type PublicKey, PublicKeys } from '@aztec/aztec.js/keys';
import type { Wallet } from '@aztec/aztec.js/wallet';
import SubscriptionFPCContractArtifactJson from '../target/subscription_fpc-SubscriptionFPC.json' with { type: 'json' };
export const SubscriptionFPCContractArtifact = loadContractArtifact(SubscriptionFPCContractArtifactJson as NoirCompiledContract);



/**
 * Type-safe interface for contract SubscriptionFPC;
 */
export class SubscriptionFPCContract extends ContractBase {
  
  private constructor(
    address: AztecAddress,
    wallet: Wallet,
  ) {
    super(address, SubscriptionFPCContractArtifact, wallet);
  }
  

  
  /**
   * Creates a contract instance.
   * @param address - The deployed contract's address.
   * @param wallet - The wallet to use when interacting with the contract.
   * @returns A new Contract instance.
   */
  public static at(
    address: AztecAddress,
    wallet: Wallet,
  ): SubscriptionFPCContract {
    return Contract.at(address, SubscriptionFPCContract.artifact, wallet) as SubscriptionFPCContract;
  }

  
  /**
   * Creates a tx to deploy a new instance of this contract.
   */
  public static deploy(wallet: Wallet, admin: AztecAddressLike) {
    return new DeployMethod<SubscriptionFPCContract>(PublicKeys.default(), wallet, SubscriptionFPCContractArtifact, (instance, wallet) => SubscriptionFPCContract.at(instance.address, wallet), Array.from(arguments).slice(1));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified public keys hash to derive the address.
   */
  public static deployWithPublicKeys(publicKeys: PublicKeys, wallet: Wallet, admin: AztecAddressLike) {
    return new DeployMethod<SubscriptionFPCContract>(publicKeys, wallet, SubscriptionFPCContractArtifact, (instance, wallet) => SubscriptionFPCContract.at(instance.address, wallet), Array.from(arguments).slice(2));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified constructor method.
   */
  public static deployWithOpts<M extends keyof SubscriptionFPCContract['methods']>(
    opts: { publicKeys?: PublicKeys; method?: M; wallet: Wallet },
    ...args: Parameters<SubscriptionFPCContract['methods'][M]>
  ) {
    return new DeployMethod<SubscriptionFPCContract>(
      opts.publicKeys ?? PublicKeys.default(),
      opts.wallet,
      SubscriptionFPCContractArtifact,
      (instance, wallet) => SubscriptionFPCContract.at(instance.address, wallet),
      Array.from(arguments).slice(1),
      opts.method ?? 'constructor',
    );
  }
  

  
  /**
   * Returns this contract's artifact.
   */
  public static get artifact(): ContractArtifact {
    return SubscriptionFPCContractArtifact;
  }

  /**
   * Returns this contract's artifact with public bytecode.
   */
  public static get artifactForPublic(): ContractArtifact {
    return loadContractArtifactForPublic(SubscriptionFPCContractArtifactJson as NoirCompiledContract);
  }
  

  public static get storage(): ContractStorageLayout<'admin' | 'subscriptions' | 'slots'> {
      return {
        admin: {
      slot: new Fr(1n),
    },
subscriptions: {
      slot: new Fr(3n),
    },
slots: {
      slot: new Fr(4n),
    }
      } as ContractStorageLayout<'admin' | 'subscriptions' | 'slots'>;
    }
    

  /** Type-safe wrappers for the public methods exposed by the contract. */
  public declare methods: {
    
    /** _ensure_max_fee(max_fee: integer) */
    _ensure_max_fee: ((max_fee: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** constructor(admin: struct) */
    constructor: ((admin: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** count_available_slots(config_id: field) */
    count_available_slots: ((config_id: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_subscription_info(user: struct, config_id: field) */
    get_subscription_info: ((user: AztecAddressLike, config_id: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** offchain_receive(messages: struct) */
    offchain_receive: ((messages: { ciphertext: FieldLike[], recipient: AztecAddressLike, tx_hash: OptionLike<FieldLike>, anchor_block_timestamp: (bigint | number) }[]) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** public_dispatch(selector: field) */
    public_dispatch: ((selector: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** sign_up(app: struct, selector: struct, current_index: integer, max_uses: integer, max_fee: integer, max_users: integer) */
    sign_up: ((app: AztecAddressLike, selector: FunctionSelectorLike, current_index: (bigint | number), max_uses: (bigint | number), max_fee: (bigint | number), max_users: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** sponsor(call: struct, current_index: integer, user: struct) */
    sponsor: ((call: { args_hash: FieldLike, function_selector: FunctionSelectorLike, target_address: AztecAddressLike, is_public: boolean, hide_msg_sender: boolean, is_static: boolean }, current_index: (bigint | number), user: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** subscribe(call: struct, current_index: integer, user: struct) */
    subscribe: ((call: { args_hash: FieldLike, function_selector: FunctionSelectorLike, target_address: AztecAddressLike, is_public: boolean, hide_msg_sender: boolean, is_static: boolean }, current_index: (bigint | number), user: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** sync_state(scope: struct) */
    sync_state: ((scope: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;
  };

  
}
