export interface SubscriptionFPCConfig {
  /** Address of the SubscriptionFPC contract */
  address: string;
  /** Secret key for registering the FPC in PXE (needed to decrypt slot notes) */
  secretKey: string;
  /** Map of contractAddress → { functionSelector → configIndex } */
  functions: Record<string, Record<string, number>>;
}

export interface NetworkConfig {
  id: string;
  nodeUrl: string;
  chainId: string;
  rollupVersion: string;
  contracts: {
    gregoCoin: string;
    gregoCoinPremium: string;
    amm: string;
    liquidityToken: string;
    pop: string;
    sponsoredFPC: string;
    salt: string;
  };
  deployer: {
    address: string;
  };
  deployedAt: string;
  /** Subscription-based FPC for sponsored transactions (operator-managed) */
  subscriptionFPC?: SubscriptionFPCConfig;
}

// Load all network configs using Vite's glob import with eager loading
// These files are generated by running: yarn deploy:local or yarn deploy:devnet
const networkModules = import.meta.glob<{ default: NetworkConfig }>("./*.json", { eager: true });

function loadNetworkConfigs(): NetworkConfig[] {
  const configs: NetworkConfig[] = [];

  // Load all JSON files in this directory
  for (const path in networkModules) {
    // Skip placeholder file
    if (path.includes("placeholder.json")) {
      continue;
    }

    try {
      const module = networkModules[path];
      configs.push(module.default);
    } catch (err) {
      // Config file not available or invalid - silently ignore
    }
  }

  // In production, exclude local network
  const filtered = import.meta.env.PROD ? configs.filter((n) => n.id !== "local") : configs;

  return filtered;
}

// Helper to initialize the networks (called by NetworkProvider)
export function initializeNetworks(): NetworkConfig[] {
  return loadNetworkConfigs();
}

// Helper to get network by id from an array
export function getNetworkById(networks: NetworkConfig[], id: string): NetworkConfig | undefined {
  return networks.find((n) => n.id === id);
}
