#!/usr/bin/env bash
# Compiles the Solidity contract and generates TypeScript artifacts.
# Usage: cd packages/ethereum/contracts && ./generate-artifacts.sh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

echo "Compiling with forge..."
forge build

ARTIFACT="out/GregoJuiceBridge.sol/GregoJuiceBridge.json"
OUTPUT_DIR="../generated"
OUTPUT="$OUTPUT_DIR/bridge-contract-artifacts.ts"

mkdir -p "$OUTPUT_DIR"

echo "Generating TypeScript artifacts..."
python3 -c "
import json

with open('$ARTIFACT') as f:
    d = json.load(f)

abi = [e for e in d['abi'] if e.get('type') == 'function']
bytecode = '0x' + d['bytecode']['object'][2:]

print('// Auto-generated by generate-artifacts.sh — do not edit manually')
print('import type { Hex } from \"viem\";')
print()
print('export const BRIDGE_CONTRACT_ABI = ' + json.dumps(abi, indent=2) + ' as const;')
print()
print('export const BRIDGE_CONTRACT_BYTECODE = \"' + bytecode + '\" as Hex;')
" > "$OUTPUT"

echo "Written to $OUTPUT"
